[package]
name = "zlib-bench"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "zlib_bench"
harness = false

[dependencies]
flate2 = { version = "1", features = ["zlib-rs"], default-features = false }

[dev-dependencies]
criterion = "0.5"

